@startuml
class PurchaseTotalDiscountRule {
    + MinimumAmount : decimal <<get>> <<set>>
    + DiscountPercent : decimal <<get>> <<set>>
    + PurchaseTotalDiscountRule()
    + PurchaseTotalDiscountRule(ruleId:string, name:string, isActive:bool, minimumAmount:decimal, discountPercent:decimal)
    + <<override>> Apply(cart:Cart, inventory:Inventory) : decimal
    + <<override>> GetDisplayInformation() : string
}
DiscountRule <|-- PurchaseTotalDiscountRule
IDiscountable <|-- PurchaseTotalDiscountRule
@enduml
